---

- name: Ensure certdeploy is installed with pipx
  community.general.pipx:
    name: certdeploy
    state: install
  environment:
    PIPX_HOME: "{{ certdeploy_client_install_pipx_home }}"
    PIPX_BIN_DIR: "{{ certdeploy_client_install_pipx_bin_dir }}"
    
- name: Merge default certdeploy-client config
  vars:
    __default_config:
      source: "{{ certdeploy_client_config_source }}"
      sftpd:
        server_pubkey: "{{ certdeploy_client_config_sftpd_server_pubkey
          | default(certdeploy_client_server_pubkey) }}"
        privkey_filename: "{{ certdeploy_client_config_dir }}/client_key"
        listen_port: "{{ certdeploy_client_config_sftpd_listen_port 
          | default(certdeploy_client_listen_port)}}"
  ansible.builtin.set_fact:
    _config: "{{ __default_config | combine(certdeploy_client_config, recursive=true) }}"

- name: Ensure certdeploy-client specific directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "{{ certdeploy_client_directory_mode }}"
    owner: "{{ certdeploy_client_uid }}"
    group: "{{ certdeploy_client_gid }}"
    recurse: yes
  loop:
    - "{{ certdeploy_client_config_dir }}"
    - "{{ _config.source }}"
    - "{{ _config.destination }}"

- name: Ensure install directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 'u=rwX,g=rX,o=rX'
    owner: root
    group: root
  loop:
    - "{{ certdeploy_client_install_lib_systemd_system }}"

- name: Install certdeploy-client privkey
  ansible.builtin.copy:
    content: "{{ certdeploy_client_privkey }}"
    dest: "{{ _config.sftpd.privkey_filename }}"
    mode: "{{ certdeploy_client_mode }}"
    owner: "{{ certdeploy_client_uid }}"
    group: "{{ certdeploy_client_gid }}"
  no_log: yes
  notify: RestartCertdeployClient

- name: Install certdeploy-client config
  ansible.builtin.copy:
    content: '{{ _config
      | to_nice_yaml
      | regex_replace("[''""]([0-9]+(.[0-9]+)?)[''""]", "\1") }}' # strip quotes from numbers
    dest: "{{ certdeploy_client_config_dir }}/client.yml"
    mode: "{{ certdeploy_client_mode }}"
    owner: "{{ certdeploy_client_uid }}"
    group: "{{ certdeploy_client_gid }}"
  notify: RestartCertdeployClient

- name: Install certdeploy-client systemd service file
  ansible.builtin.template:
    src: templates/certdeploy-client.service.j2
    dest: "{{ certdeploy_client_install_lib_systemd_system }}/certdeploy-client.service"
    mode: '0644'
    owner: "{{ certdeploy_client_service_file_owner }}"
    group: "{{ certdeploy_client_service_file_group }}"
  notify: RestartCertdeployClient

- name: Ensure service is enabled and restarted
  ansible.builtin.systemd_service:
    name: certdeploy-client.service
    state: started
    enabled: yes
